var shuffleSequence = seq("intro", sepWith("sep", rshuffle(endsWith("w"), endsWith("p"), endsWith("n"))));

var defaults = [
  "Separator", {
    transfer: 500,
    normalMessage: "Please wait for the next word.",
    errorMessage: "Wrong. Please wait for the next sentence."
  },
  "AcceptabilityJudgment", {
    q: "Hversu eðlilegt og náttúrulegt væri þetta sem íslenskt orð?",
    as: ["1", "2", "3", "4", "5", "6", "7", "8"],
    presentAsScale: true,
    instructions: "Use number keys or click boxes to answer.",
    leftComment: "(Út í hött)", rightComment: "(Alvöru íslenskt orð)"
  },
  "Message", {
    hideProgressBar: true
  },
  "Form", {
    hideProgressBar: true,
    continueOnReturn: true,
    saveReactionTime: true
  },
  "Question", {
    as: ["Já", "Nei"],
  }
];

var items = [
  ["sep", "Separator", { }],

  ["intro", "Message", {
    html: { include: "instructions.html" },
  }],

  ["1w", "AcceptabilityJudgment", {s: "dagur"}],
  ["2w", "AcceptabilityJudgment", {s: "vegur"}],
  ["3w", "AcceptabilityJudgment", {s: "starf"}],
  ["4w", "AcceptabilityJudgment", {s: "hluti"}],
  ["5w", "AcceptabilityJudgment", {s: "krafa"}],
  ["6w", "AcceptabilityJudgment", {s: "grein"}],
  ["7w", "AcceptabilityJudgment", {s: "deild"}],
  ["8w", "AcceptabilityJudgment", {s: "banki"}],
  ["9w", "AcceptabilityJudgment", {s: "sumar"}],
  ["10w", "AcceptabilityJudgment", {s: "sigur"}],
  ["11w", "AcceptabilityJudgment", {s: "munur"}],
  ["12w", "AcceptabilityJudgment", {s: "nefnd"}],
  ["13w", "AcceptabilityJudgment", {s: "leyti"}],
  ["14w", "AcceptabilityJudgment", {s: "vinna"}],
  ["15w", "AcceptabilityJudgment", {s: "regla"}],
  ["16w", "AcceptabilityJudgment", {s: "helgi"}],
  ["17w", "AcceptabilityJudgment", {s: "vinur"}],
  ["18w", "AcceptabilityJudgment", {s: "stund"}],
  ["19w", "AcceptabilityJudgment", {s: "tekja"}],
  ["20w", "AcceptabilityJudgment", {s: "gildi"}],
  ["21w", "AcceptabilityJudgment", {s: "herra"}],
  ["22w", "AcceptabilityJudgment", {s: "aldur"}],
  ["23w", "AcceptabilityJudgment", {s: "gaman"}],
  ["24w", "AcceptabilityJudgment", {s: "vitni"}],
  ["25w", "AcceptabilityJudgment", {s: "haust"}],
  ["26w", "AcceptabilityJudgment", {s: "vetur"}],
  ["27w", "AcceptabilityJudgment", {s: "kafli"}],
  ["28w", "AcceptabilityJudgment", {s: "bolti"}],
  ["29w", "AcceptabilityJudgment", {s: "leyfi"}],
  ["30w", "AcceptabilityJudgment", {s: "sonur"}],
  ["31w", "AcceptabilityJudgment", {s: "skuld"}],
  ["32w", "AcceptabilityJudgment", {s: "kerfi"}],
  ["33w", "AcceptabilityJudgment", {s: "heild"}],
  ["34w", "AcceptabilityJudgment", {s: "metri"}],
  ["35w", "AcceptabilityJudgment", {s: "sveit"}],
  ["36w", "AcceptabilityJudgment", {s: "vandi"}],
  ["37w", "AcceptabilityJudgment", {s: "vefur"}],
  ["38w", "AcceptabilityJudgment", {s: "listi"}],
  ["39w", "AcceptabilityJudgment", {s: "plata"}],
  ["40w", "AcceptabilityJudgment", {s: "atvik"}],
  ["41w", "AcceptabilityJudgment", {s: "hugur"}],
  ["42w", "AcceptabilityJudgment", {s: "gjald"}],
  ["43w", "AcceptabilityJudgment", {s: "gengi"}],
  ["44w", "AcceptabilityJudgment", {s: "lausn"}],
  ["45w", "AcceptabilityJudgment", {s: "matur"}],
  ["46w", "AcceptabilityJudgment", {s: "skref"}],
  ["47w", "AcceptabilityJudgment", {s: "pabbi"}],
  ["48w", "AcceptabilityJudgment", {s: "merki"}],
  ["49w", "AcceptabilityJudgment", {s: "braut"}],
  ["50w", "AcceptabilityJudgment", {s: "deila"}],
  ["51w", "AcceptabilityJudgment", {s: "kynni"}],
  ["52w", "AcceptabilityJudgment", {s: "fylgi"}],
  ["53w", "AcceptabilityJudgment", {s: "fjall"}],
  ["54w", "AcceptabilityJudgment", {s: "skjal"}],
  ["55w", "AcceptabilityJudgment", {s: "enska"}],
  ["56w", "AcceptabilityJudgment", {s: "kaffi"}],
  ["57w", "AcceptabilityJudgment", {s: "ganga"}],
  ["58w", "AcceptabilityJudgment", {s: "messa"}],
  ["59w", "AcceptabilityJudgment", {s: "leiga"}],
  ["60w", "AcceptabilityJudgment", {s: "ferli"}],
  ["1p", "AcceptabilityJudgment", {s: "rudag"}],
  ["2p", "AcceptabilityJudgment", {s: "ruveg"}],
  ["3p", "AcceptabilityJudgment", {s: "farst"}],
  ["4p", "AcceptabilityJudgment", {s: "tuhil"}],
  ["5p", "AcceptabilityJudgment", {s: "afkra"}],
  ["6p", "AcceptabilityJudgment", {s: "ergin"}],
  ["7p", "AcceptabilityJudgment", {s: "didel"}],
  ["8p", "AcceptabilityJudgment", {s: "kinba"}],
  ["9p", "AcceptabilityJudgment", {s: "marus"}],
  ["10p", "AcceptabilityJudgment", {s: "gusir"}],
  ["11p", "AcceptabilityJudgment", {s: "rumun"}],
  ["12p", "AcceptabilityJudgment", {s: "fennd"}],
  ["13p", "AcceptabilityJudgment", {s: "tiley"}],
  ["14p", "AcceptabilityJudgment", {s: "nivan"}],
  ["15p", "AcceptabilityJudgment", {s: "raleg"}],
  ["16p", "AcceptabilityJudgment", {s: "hlige"}],
  ["17p", "AcceptabilityJudgment", {s: "rivun"}],
  ["18p", "AcceptabilityJudgment", {s: "nudst"}],
  ["19p", "AcceptabilityJudgment", {s: "kjate"}],
  ["20p", "AcceptabilityJudgment", {s: "lidig"}],
  ["21p", "AcceptabilityJudgment", {s: "rehar"}],
  ["22p", "AcceptabilityJudgment", {s: "rulda"}],
  ["23p", "AcceptabilityJudgment", {s: "namga"}],
  ["24p", "AcceptabilityJudgment", {s: "tivin"}],
  ["25p", "AcceptabilityJudgment", {s: "husat"}],
  ["26p", "AcceptabilityJudgment", {s: "trevu"}],
  ["27p", "AcceptabilityJudgment", {s: "filak"}],
  ["28p", "AcceptabilityJudgment", {s: "tolbi"}],
  ["29p", "AcceptabilityJudgment", {s: "lifey"}],
  ["30p", "AcceptabilityJudgment", {s: "rosun"}],
  ["31p", "AcceptabilityJudgment", {s: "dulsk"}],
  ["32p", "AcceptabilityJudgment", {s: "refik"}],
  ["33p", "AcceptabilityJudgment", {s: "hedli"}],
  ["34p", "AcceptabilityJudgment", {s: "ritem"}],
  ["35p", "AcceptabilityJudgment", {s: "sivet"}],
  ["36p", "AcceptabilityJudgment", {s: "davin"}],
  ["37p", "AcceptabilityJudgment", {s: "furev"}],
  ["38p", "AcceptabilityJudgment", {s: "tisil"}],
  ["39p", "AcceptabilityJudgment", {s: "aplat"}],
  ["40p", "AcceptabilityJudgment", {s: "kivat"}],
  ["41p", "AcceptabilityJudgment", {s: "guruh"}],
  ["42p", "AcceptabilityJudgment", {s: "ljagd"}],
  ["43p", "AcceptabilityJudgment", {s: "engig"}],
  ["44p", "AcceptabilityJudgment", {s: "nusal"}],
  ["45p", "AcceptabilityJudgment", {s: "tumar"}],
  ["46p", "AcceptabilityJudgment", {s: "ferks"}],
  ["47p", "AcceptabilityJudgment", {s: "bapib"}],
  ["48p", "AcceptabilityJudgment", {s: "mirke"}],
  ["49p", "AcceptabilityJudgment", {s: "tubra"}],
  ["50p", "AcceptabilityJudgment", {s: "lidea"}],
  ["51p", "AcceptabilityJudgment", {s: "ynnik"}],
  ["52p", "AcceptabilityJudgment", {s: "glyfi"}],
  ["53p", "AcceptabilityJudgment", {s: "ljafl"}],
  ["54p", "AcceptabilityJudgment", {s: "jalks"}],
  ["55p", "AcceptabilityJudgment", {s: "kensa"}],
  ["56p", "AcceptabilityJudgment", {s: "affik"}],
  ["57p", "AcceptabilityJudgment", {s: "angag"}],
  ["58p", "AcceptabilityJudgment", {s: "mesas"}],
  ["59p", "AcceptabilityJudgment", {s: "aglei"}],
  ["60p", "AcceptabilityJudgment", {s: "lefir"}],
  ["1n ", "AcceptabilityJudgment", {s: "gdura"}],
  ["2n ", "AcceptabilityJudgment", {s: "vgrue"}],
  ["3n ", "AcceptabilityJudgment", {s: "tfsar"}],
  ["4n ", "AcceptabilityJudgment", {s: "htlui"}],
  ["5n ", "AcceptabilityJudgment", {s: "kfraa"}],
  ["6n ", "AcceptabilityJudgment", {s: "rgnie"}],
  ["7n ", "AcceptabilityJudgment", {s: "ldedi"}],
  ["8n ", "AcceptabilityJudgment", {s: "kbina"}],
  ["9n ", "AcceptabilityJudgment", {s: "rsuma"}],
  ["10n", "AcceptabilityJudgment", {s: "rgsiu"}],
  ["11n", "AcceptabilityJudgment", {s: "rnumu"}],
  ["12n", "AcceptabilityJudgment", {s: "dfenn"}],
  ["13n", "AcceptabilityJudgment", {s: "tliey"}],
  ["14n", "AcceptabilityJudgment", {s: "vnnia"}],
  ["15n", "AcceptabilityJudgment", {s: "rglae"}],
  ["16n", "AcceptabilityJudgment", {s: "lgehi"}],
  ["17n", "AcceptabilityJudgment", {s: "nvriu"}],
  ["18n", "AcceptabilityJudgment", {s: "tndus"}],
  ["19n", "AcceptabilityJudgment", {s: "tjkae"}],
  ["20n", "AcceptabilityJudgment", {s: "lgdii"}],
  ["21n", "AcceptabilityJudgment", {s: "rhrae"}],
  ["22n", "AcceptabilityJudgment", {s: "ualdr"}],
  ["23n", "AcceptabilityJudgment", {s: "aamgn"}],
  ["24n", "AcceptabilityJudgment", {s: "tniiv"}],
  ["25n", "AcceptabilityJudgment", {s: "tshau"}],
  ["26n", "AcceptabilityJudgment", {s: "rtuev"}],
  ["27n", "AcceptabilityJudgment", {s: "lkfai"}],
  ["28n", "AcceptabilityJudgment", {s: "tbiol"}],
  ["29n", "AcceptabilityJudgment", {s: "lfeyi"}],
  ["30n", "AcceptabilityJudgment", {s: "rnsuo"}],
  ["31n", "AcceptabilityJudgment", {s: "udksl"}],
  ["32n", "AcceptabilityJudgment", {s: "krfei"}],
  ["33n", "AcceptabilityJudgment", {s: "eihdl"}],
  ["34n", "AcceptabilityJudgment", {s: "tmrei"}],
  ["35n", "AcceptabilityJudgment", {s: "tvsie"}],
  ["36n", "AcceptabilityJudgment", {s: "dvnia"}],
  ["37n", "AcceptabilityJudgment", {s: "rvuef"}],
  ["38n", "AcceptabilityJudgment", {s: "iitsl"}],
  ["39n", "AcceptabilityJudgment", {s: "ptaal"}],
  ["40n", "AcceptabilityJudgment", {s: "vkiat"}],
  ["41n", "AcceptabilityJudgment", {s: "ghuur"}],
  ["42n", "AcceptabilityJudgment", {s: "jdgla"}],
  ["43n", "AcceptabilityJudgment", {s: "ngeig"}],
  ["44n", "AcceptabilityJudgment", {s: "nlsau"}],
  ["45n", "AcceptabilityJudgment", {s: "rtaum"}],
  ["46n", "AcceptabilityJudgment", {s: "fksre"}],
  ["47n", "AcceptabilityJudgment", {s: "bbpai"}],
  ["48n", "AcceptabilityJudgment", {s: "rmkie"}],
  ["49n", "AcceptabilityJudgment", {s: "rtabu"}],
  ["50n", "AcceptabilityJudgment", {s: "dieal"}],
  ["51n", "AcceptabilityJudgment", {s: "nknyi"}],
  ["52n", "AcceptabilityJudgment", {s: "fgliy"}],
  ["53n", "AcceptabilityJudgment", {s: "lflaj"}],
  ["54n", "AcceptabilityJudgment", {s: "lksaj"}],
  ["55n", "AcceptabilityJudgment", {s: "nskae"}],
  ["56n", "AcceptabilityJudgment", {s: "fkiaf"}],
  ["57n", "AcceptabilityJudgment", {s: "gngaa"}],
  ["58n", "AcceptabilityJudgment", {s: "mssae"}],
  ["59n", "AcceptabilityJudgment", {s: "lgiae"}],
  ["60n", "AcceptabilityJudgment", {s: "rlfei"}]
];
